-- CREAZIONE UTENTE

CREATE ROLE www WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	BYPASSRLS
	CONNECTION LIMIT -1
	PASSWORD 'xxxxxx';

-- CREAZIONE DATABASE

CREATE DATABASE gruppo38
    WITH
    OWNER = www
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- CREAZIONE TABELLA

DROP TABLE IF EXISTS utente cascade;
CREATE TABLE utente(
id serial PRIMARY KEY,
username varchar(255),
email varchar(255),
password varchar(255)
);
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO www;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO www;

-- INSERIMENTO TABELLA

INSERT INTO utente (username, email, password)
VALUES (Michele, michelepio44@gmail.com, $2y$10$rCvNW1/ZIFfP6eoIbZq15.4bJZ60hDg6QpSUQb9XMLm5/tLbqhHkG); --1234